site_name: SQL Tasks
repo_url: https://github.com/systopia/de.systopia.sqltasks
theme: material

nav:
- 'Home': index.md
- 'Installation': installation.md
- 'Usage': usage.md
- 'Example': example.md
- 'Security considerations': security-considerations.md
- 'Known issues': known-issues.md

markdown_extensions:
- attr_list
- admonition
- def_list
- codehilite
- toc:
    permalink: true
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.tilde
- pymdownx.betterem
- pymdownx.mark
